#!/usr/bin/env bash
# Project-side cluster automation for robust-meme-hate-detection.
# Adapted from cluster-access-tutorial/scripts/cluster.sh, with the
# fruit-dataset and practice-3 specifics replaced by Hateful-Memes
# specifics. The dataset is staged on /scratch/datasets/hate_meta and is
# read-only, so there is no `sync-data` command in this project.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/cluster"
CONFIG_FILE="$CONFIG_DIR/config.env"
LOCAL_CONFIG_FILE="$CONFIG_DIR/config.local.env"
STATE_FILE="$CONFIG_DIR/state.local.env"
SYNC_EXCLUDE_FILE="$CONFIG_DIR/sync-code.exclude"
LOCAL_RESULTS_DIR="$REPO_ROOT/cluster-results"
LOCAL_CHECKPOINTS_DIR="$REPO_ROOT/cluster-checkpoints"

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
print_check() { printf '%-18s %s\n' "$1" "$2"; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"; }

load_config() {
    [[ -f "$CONFIG_FILE" ]] || die "Missing config file: $CONFIG_FILE"
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
    [[ -f "$LOCAL_CONFIG_FILE" ]] && source "$LOCAL_CONFIG_FILE"
    [[ -f "$STATE_FILE" ]] && source "$STATE_FILE"

    : "${SSH_HOST:?Missing SSH_HOST in config}"
    : "${RUNAI_PROJECT:?Missing RUNAI_PROJECT in config}"
    : "${REMOTE_HOME:?Missing REMOTE_HOME in config}"
    : "${REMOTE_PROJECT_DIR:?Missing REMOTE_PROJECT_DIR in config}"
    : "${REMOTE_SCRATCH_DIR:?Missing REMOTE_SCRATCH_DIR in config}"
    : "${REMOTE_SCRATCH_PROJECT_DIR:?Missing REMOTE_SCRATCH_PROJECT_DIR in config}"
    : "${SCRATCH_PVC:?Missing SCRATCH_PVC in config}"
    : "${HOME_PVC:?Missing HOME_PVC in config}"
    : "${SCRATCH_MOUNT:?Missing SCRATCH_MOUNT in config}"
    : "${HOME_MOUNT:?Missing HOME_MOUNT in config}"
    : "${JOB_DATA_ROOT:?Missing JOB_DATA_ROOT in config}"
    : "${JOB_RESULTS_ROOT:?Missing JOB_RESULTS_ROOT in config}"
    : "${BASE_IMAGE:?Missing BASE_IMAGE in config}"
    : "${IMAGE_REPO:?Missing IMAGE_REPO in config}"
    : "${IMAGE_TAG:?Missing IMAGE_TAG in config}"
    : "${DEFAULT_IMAGE:?Missing DEFAULT_IMAGE in config}"
    : "${CUSTOM_IMAGE:?Missing CUSTOM_IMAGE in config}"
    : "${REMOTE_UID:?Missing REMOTE_UID in config}"
    : "${RUNAI_GPU:?Missing RUNAI_GPU in config}"
}

run_remote_script() {
    local script="$1"; shift
    ssh -o BatchMode=yes "$SSH_HOST" bash -s -- "$@" <<<"$script"
}

runai_remote() {
    run_remote_script 'set -euo pipefail
project="$1"; shift
SUPPRESS_DEPRECATION_MESSAGE=true runai config project "$project" >/dev/null
SUPPRESS_DEPRECATION_MESSAGE=true runai "$@"
' "$RUNAI_PROJECT" "$@"
}

ensure_remote_dir() { run_remote_script 'set -euo pipefail; mkdir -p "$1"' "$1"; }
ensure_remote_code_dir() { ensure_remote_dir "$REMOTE_PROJECT_DIR"; }
ensure_remote_scratch_dirs() {
    ensure_remote_dir "$REMOTE_SCRATCH_PROJECT_DIR"
    ensure_remote_dir "$REMOTE_SCRATCH_PROJECT_DIR/experiments"
}

write_state_image() {
    local image_ref="$1"
    mkdir -p "$CONFIG_DIR"
    cat >"$STATE_FILE" <<EOF
# Generated by cluster/cluster.sh
ACTIVE_IMAGE=$image_ref
EOF
}

current_image_ref() { printf '%s\n' "${ACTIVE_IMAGE:-$DEFAULT_IMAGE}"; }
custom_image_ref() { local tag="${1:-$IMAGE_TAG}"; printf '%s:%s\n' "$IMAGE_REPO" "$tag"; }
git_short_sha() { git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || printf 'nogit'; }
timestamp_utc() { date -u +%Y%m%d-%H%M%S; }
default_job_name() { printf '%s-%s-%s\n' "$1" "$(timestamp_utc)" "$(git_short_sha)"; }
docker_image_ready() { docker image inspect "$1" >/dev/null 2>&1; }

job_status_value() {
    runai_remote describe job "$1" | awk -F': ' '/^Status:/ {print $2; exit}'
}

job_pod_name() {
    local job_name="$1"
    runai_remote describe job "$job_name" | awk -v job_name="$job_name" '
        $1 == "Pods:" {in_pods=1; next}
        $1 == "Events:" {in_pods=0}
        in_pods && $1 ~ ("^" job_name "-") {print $1; exit}
    '
}

job_is_terminal() {
    case "$1" in Succeeded|Failed|Cancelled|Deleted) return 0 ;; *) return 1 ;; esac
}

emit_new_job_logs() {
    local job_name="$1"; local pod_name="$2"; local cursor_file="$3"
    local last_lines=0 current_logs current_lines
    [[ -f "$cursor_file" ]] && read -r last_lines <"$cursor_file" || true
    current_logs="$(runai_remote logs "$job_name" --pod "$pod_name" --tail 2000 2>/dev/null || true)"
    [[ -n "$current_logs" ]] || return 0
    current_lines=$(printf '%s\n' "$current_logs" | wc -l | tr -d ' ')
    (( current_lines < last_lines )) && last_lines=0
    if (( current_lines > last_lines )); then
        printf '%s\n' "$current_logs" | sed -n "$((last_lines + 1)),\$p" >&2
        printf '%s\n' "$current_lines" >"$cursor_file"
    fi
}

wait_for_job_completion() {
    local job_name="$1"; local poll_seconds="${2:-5}"
    local last_status="" pod_name="" status=""
    local cursor_file
    cursor_file="$(mktemp)"
    # Use a function-scoped trap; the inner expansion happens before scope ends.
    trap "rm -f $cursor_file" RETURN
    while true; do
        status="$(job_status_value "$job_name")"
        if [[ "$status" != "$last_status" ]]; then
            printf 'job=%s status=%s\n' "$job_name" "$status" >&2
            last_status="$status"
        fi
        if [[ -z "$pod_name" ]]; then
            pod_name="$(job_pod_name "$job_name" || true)"
            [[ -n "$pod_name" ]] && printf 'job=%s pod=%s\n' "$job_name" "$pod_name" >&2
        fi
        [[ -n "$pod_name" ]] && emit_new_job_logs "$job_name" "$pod_name" "$cursor_file"
        if job_is_terminal "$status"; then
            printf 'job=%s final_status=%s\n' "$job_name" "$status" >&2
            printf '%s\n' "$status"
            return 0
        fi
        sleep "$poll_seconds"
    done
}

runai_mount_args() {
    printf '%s\0' \
        --existing-pvc "claimname=$SCRATCH_PVC,path=$SCRATCH_MOUNT" \
        --existing-pvc "claimname=$HOME_PVC,path=$HOME_MOUNT"
}

# Submit a Run:AI job with the standard mounts and an arbitrary command.
# Args: $1 mode (interactive|batch), $2 job_name, $3 image_ref, then the command tokens.
submit_runai_job() {
    local mode="$1"; local job_name="$2"; local image_ref="$3"; shift 3
    local -a cmd_tokens=("$@")
    local -a submit_args mount_args
    ensure_remote_scratch_dirs
    while IFS= read -r -d '' item; do mount_args+=("$item"); done < <(runai_mount_args)
    submit_args=(
        submit
        --name "$job_name"
        --image "$image_ref"
        --gpu "$RUNAI_GPU"
        --run-as-uid "$REMOTE_UID"
        --large-shm
        "${mount_args[@]}"
    )
    if [[ "$mode" == "interactive" ]]; then
        submit_args+=(--interactive)
        runai_remote "${submit_args[@]}"
        return
    fi
    submit_args+=(--command -- "${cmd_tokens[@]}")
    runai_remote "${submit_args[@]}"
}

cmd_doctor() {
    local failures=0 tool
    for tool in ssh rsync docker git; do
        if command -v "$tool" >/dev/null 2>&1; then
            print_check "$tool" "ok ($(command -v "$tool"))"
        else
            print_check "$tool" "missing"; failures=1
        fi
    done
    command -v codex >/dev/null 2>&1 \
        && print_check "codex" "ok ($(command -v codex))" \
        || print_check "codex" "missing"
    if docker version >/dev/null 2>&1; then
        print_check "docker daemon" "ok"
    else
        print_check "docker daemon" "failed"; failures=1
    fi
    [[ -f "$CONFIG_FILE" ]] && print_check "config" "ok ($CONFIG_FILE)" \
                            || { print_check "config" "missing"; failures=1; }
    [[ -f "$SYNC_EXCLUDE_FILE" ]] && print_check "sync excludes" "ok ($SYNC_EXCLUDE_FILE)" \
                                  || { print_check "sync excludes" "missing"; failures=1; }
    if ssh -o BatchMode=yes "$SSH_HOST" "echo connected" >/dev/null; then
        print_check "ssh batch mode" "ok"
    else
        print_check "ssh batch mode" "failed"; failures=1
    fi
    if runai_remote list >/dev/null 2>&1; then
        print_check "remote runai" "ok ($RUNAI_PROJECT)"
    else
        print_check "remote runai" "failed"; failures=1
    fi
    if run_remote_script 'set -euo pipefail; [[ -d "$1" ]]' "$REMOTE_SCRATCH_DIR"; then
        print_check "remote scratch" "ok ($REMOTE_SCRATCH_DIR)"
    else
        print_check "remote scratch" "failed"; failures=1
    fi
    if run_remote_script 'set -euo pipefail; [[ -d "$1" ]] && [[ -f "$1/train.jsonl" ]]' \
            "$REMOTE_SCRATCH_DIR/datasets/hate_meta"; then
        print_check "staged dataset" "ok ($REMOTE_SCRATCH_DIR/datasets/hate_meta)"
    else
        print_check "staged dataset" "failed"; failures=1
    fi
    print_check "repo root" "$REPO_ROOT"
    print_check "ssh host" "$SSH_HOST"
    print_check "remote code dir" "$REMOTE_PROJECT_DIR"
    print_check "active image" "$(current_image_ref)"
    (( failures == 0 )) || die "doctor failed"
}

cmd_ssh() {
    if (( $# == 0 )); then exec ssh "$SSH_HOST"; fi
    exec ssh "$SSH_HOST" "$@"
}

cmd_remote_check() {
    run_remote_script 'set -euo pipefail
runai_project="$1"; scratch_dir="$2"
echo "connected"; id
echo "remote_user=$USER"; echo "remote_home=$HOME"
echo "remote_scratch=$scratch_dir"
SUPPRESS_DEPRECATION_MESSAGE=true runai config project "$runai_project" >/dev/null
echo "runai_project=$runai_project"
echo "--- staged dataset ---"
ls -la "$scratch_dir/datasets/hate_meta" | head -10 || true
SUPPRESS_DEPRECATION_MESSAGE=true runai list
' "$RUNAI_PROJECT" "$REMOTE_SCRATCH_DIR"
}

cmd_runai_list() { runai_remote list; }

cmd_sync_code() {
    need_cmd rsync
    [[ -f "$SYNC_EXCLUDE_FILE" ]] || die "Missing sync exclude file: $SYNC_EXCLUDE_FILE"
    ensure_remote_code_dir
    rsync -az --delete \
        --exclude-from="$SYNC_EXCLUDE_FILE" \
        -e "ssh -o BatchMode=yes" \
        "$REPO_ROOT/" \
        "$SSH_HOST:$REMOTE_PROJECT_DIR/"
    printf 'Synced code to %s:%s/\n' "$SSH_HOST" "$REMOTE_PROJECT_DIR"
}

cmd_pull_results() {
    local job_name="${1:-}"
    local remote_source="$REMOTE_SCRATCH_PROJECT_DIR/experiments/"
    local local_target="$LOCAL_RESULTS_DIR/"
    need_cmd rsync
    mkdir -p "$LOCAL_RESULTS_DIR"
    if [[ -n "$job_name" ]]; then
        remote_source="$REMOTE_SCRATCH_PROJECT_DIR/experiments/$job_name/"
        local_target="$LOCAL_RESULTS_DIR/$job_name/"
    fi
    rsync -az -e "ssh -o BatchMode=yes" "$SSH_HOST:$remote_source" "$local_target"
    printf 'Pulled results from %s:%s to %s\n' "$SSH_HOST" "$remote_source" "$local_target"
}

cmd_pull_artifacts() { cmd_pull_results "$@"; }

cmd_pull_checkpoints() {
    local job_name="${1:-}"
    local remote_source="$REMOTE_SCRATCH_PROJECT_DIR/experiments/"
    local local_target="$LOCAL_CHECKPOINTS_DIR/"
    need_cmd rsync
    mkdir -p "$LOCAL_CHECKPOINTS_DIR"
    if [[ -n "$job_name" ]]; then
        remote_source="$REMOTE_SCRATCH_PROJECT_DIR/experiments/$job_name/ckpt/"
        local_target="$LOCAL_CHECKPOINTS_DIR/$job_name/"
        rsync -az -e "ssh -o BatchMode=yes" "$SSH_HOST:$remote_source" "$local_target"
        printf 'Pulled checkpoints from %s:%s to %s\n' "$SSH_HOST" "$remote_source" "$local_target"
        return
    fi
    rsync -az --prune-empty-dirs \
        --include='*/' --include='ckpt/***' --exclude='*' \
        -e "ssh -o BatchMode=yes" \
        "$SSH_HOST:$remote_source" "$local_target"
    printf 'Pulled checkpoints from %s:%s to %s\n' "$SSH_HOST" "$remote_source" "$local_target"
}

cmd_build_image() {
    local image_ref
    need_cmd docker
    [[ $# -gt 0 ]] && image_ref="$(custom_image_ref "$1")" || image_ref="$CUSTOM_IMAGE"
    docker build -t "$image_ref" "$REPO_ROOT"
    write_state_image "$image_ref"
    printf 'Built image %s\n' "$image_ref"
}

cmd_push_image() {
    local image_ref
    need_cmd docker
    [[ $# -gt 0 ]] && image_ref="$(custom_image_ref "$1")" || image_ref="${ACTIVE_IMAGE:-$CUSTOM_IMAGE}"
    docker_image_ready "$image_ref" || die "Local image not found: $image_ref"
    docker push "$image_ref"
    write_state_image "$image_ref"
    printf 'Pushed image %s\n' "$image_ref"
}

# submit-cmd <job-name> -- <command tokens...>
cmd_submit_cmd() {
    [[ $# -ge 1 ]] || die "Usage: submit-cmd <job-name> -- <command...>"
    local job_name="$1"; shift
    [[ "${1:-}" == "--" ]] || die "Expected -- between job name and command. Got: ${1:-<empty>}"
    shift
    [[ $# -ge 1 ]] || die "Empty command after --"
    submit_runai_job batch "$job_name" "$(current_image_ref)" "$@"
}

# submit-smoke [job-name] [--config configs/smoke.yaml]
cmd_submit_smoke() {
    local job_name="${1:-$(default_job_name smoke)}"; shift || true
    local config="${SMOKE_CONFIG:-configs/smoke.yaml}"
    while (( $# > 0 )); do
        case "$1" in
            --config) config="$2"; shift 2 ;;
            *) die "Unknown flag for submit-smoke: $1" ;;
        esac
    done
    submit_runai_job batch "$job_name" "$(current_image_ref)" \
        "$JOB_CODE_DIR/scripts/cluster_entrypoint.sh" \
        robust_meme_hate_detection.tests.smoke_cluster \
        --config "$config" \
        --out "$JOB_RESULTS_ROOT/$job_name"
}

# submit-train [job-name] [--config configs/stage1.yaml] [--seed 0]
cmd_submit_train() {
    local job_name="${1:-$(default_job_name train)}"; shift || true
    local config="${TRAIN_CONFIG:-configs/stage1.yaml}"
    local seed=0
    while (( $# > 0 )); do
        case "$1" in
            --config) config="$2"; shift 2 ;;
            --seed)   seed="$2"; shift 2 ;;
            *) die "Unknown flag for submit-train: $1" ;;
        esac
    done
    submit_runai_job batch "$job_name" "$(current_image_ref)" \
        "$JOB_CODE_DIR/scripts/cluster_entrypoint.sh" \
        robust_meme_hate_detection.train.stage1 \
        --config "$config" \
        --seed "$seed" \
        --out "$JOB_RESULTS_ROOT/$job_name"
}

cmd_submit_interactive() {
    local job_name="${1:-$(default_job_name interactive)}"
    submit_runai_job interactive "$job_name" "$(current_image_ref)"
}

cmd_wait_job() {
    [[ $# -ge 1 ]] || die "Usage: wait-job <job-name> [poll-seconds]"
    wait_for_job_completion "$1" "${2:-5}"
}

cmd_job_status() {
    [[ $# -ge 1 ]] || die "Usage: job-status <job-name>"
    runai_remote describe job "$1"
}

cmd_job_logs() {
    [[ $# -ge 1 ]] || die "Usage: job-logs <job-name> [runai log flags]"
    runai_remote logs "$@"
}

cmd_job_delete() {
    [[ $# -ge 1 ]] || die "Usage: job-delete <job-name>"
    runai_remote delete job "$1"
}

cmd_summarize_results() {
    local job_name="${1:-}"
    [[ -n "$job_name" ]] || die "Usage: summarize-results <job-name>"
    local metrics_file="$LOCAL_RESULTS_DIR/$job_name/metrics.json"
    [[ -f "$metrics_file" ]] || die "Metrics file not found: $metrics_file"
    python3 - "$metrics_file" "$job_name" <<'PY'
import json, sys, pathlib
p, name = sys.argv[1], sys.argv[2]
m = json.loads(pathlib.Path(p).read_text())
def num(k, default=None):
    v = m.get(k)
    if v is None: return default
    try: return float(v)
    except (TypeError, ValueError): return default
print(f"Job: {name}")
for k in ["val_auroc","val_macro_f1","val_accuracy","val_precision","val_recall",
          "val_fpr","val_fnr","train_loss","val_loss","best_threshold","epochs"]:
    v = m.get(k)
    if v is not None:
        if isinstance(v, float): print(f"  {k:>18s} = {v:.4f}")
        else:                    print(f"  {k:>18s} = {v}")
auroc = num("val_auroc")
if auroc is None:
    print("  (no AUROC found in metrics.json)")
elif auroc >= 0.72:
    print(f"  -> dev AUROC {auroc:.4f} >= 0.72: PASSES Stage-1 acceptance bar.")
else:
    print(f"  -> dev AUROC {auroc:.4f} < 0.72: STOPS for review.")
PY
}

# run-train <job-name> [--config ...] [--seed N] [poll]
# Submits the training job, waits for completion, pulls artifacts and checkpoints, and summarizes.
cmd_run_train() {
    local job_name="${1:-$(default_job_name train)}"; shift || true
    local poll_seconds=10
    local -a passthrough=()
    while (( $# > 0 )); do
        case "$1" in
            --config|--seed) passthrough+=("$1" "$2"); shift 2 ;;
            *)
                if [[ "$1" =~ ^[0-9]+$ ]]; then poll_seconds="$1"; shift
                else die "Unknown arg for run-train: $1"; fi ;;
        esac
    done
    cmd_submit_train "$job_name" "${passthrough[@]}"
    local final_status
    final_status="$(wait_for_job_completion "$job_name" "$poll_seconds")"
    [[ "$final_status" == "Succeeded" ]] || die "Training job $job_name ended with status: $final_status"
    cmd_pull_artifacts "$job_name"
    cmd_pull_checkpoints "$job_name"
    cmd_summarize_results "$job_name"
}

cmd_interactive_bash() {
    [[ $# -ge 1 ]] || die "Usage: interactive-bash <job-name>"
    exec ssh "$SSH_HOST" "SUPPRESS_DEPRECATION_MESSAGE=true runai config project '$RUNAI_PROJECT' >/dev/null && SUPPRESS_DEPRECATION_MESSAGE=true runai bash '$1' --interactive"
}

usage() {
    cat <<EOF
Usage: $(basename "$0") <command> [args]

Commands:
  doctor                    Validate local tools, config, Docker, SSH, Run:AI access, and the staged dataset
  ssh [args]                Open an SSH session or run one remote command
  remote-check              Print remote identity, scratch path, dataset listing, and Run:AI listing
  runai-list                Run 'runai list' on the jumphost
  sync-code                 Rsync the project repo to the configured remote code directory
  pull-results [job]        Pull all results or one job's results back to ./cluster-results
  pull-artifacts [job]      Alias for pull-results
  pull-checkpoints [job]    Pull only checkpoint directories to ./cluster-checkpoints
  build-image [tag]         Build the custom image and mark it active in cluster/state.local.env
  push-image [tag]          Push the active or selected custom image to registry.rcp.epfl.ch
  submit-interactive [job]  Submit an interactive Run:AI job
  submit-smoke [job] [--config CFG]
                            Submit a short smoke-test batch job
  submit-train [job] [--config CFG] [--seed N]
                            Submit a Stage-1 training job
  submit-cmd <job> -- <cmd...>
                            Submit a Run:AI batch job with an arbitrary command (used for Stage 2/3, threshold sweep, attack grid)
  run-train [job] [--config CFG] [--seed N] [poll]
                            Submit train, monitor logs, wait, pull artifacts/checkpoints, summarize
  wait-job <job> [poll]     Poll Run:AI status and stream new logs until terminal
  job-status <job>          Show detailed Run:AI status for one job
  job-logs <job> [...]      Show Run:AI logs for one job (extra args passed to 'runai logs')
  job-delete <job>          Delete one Run:AI job
  summarize-results <job>   Read local metrics.json and print a concise evaluation
  interactive-bash <job>    Open a shell in a running interactive job
EOF
}

main() {
    local command="${1:-}"
    [[ -n "$command" ]] || { usage; exit 1; }
    load_config
    shift
    case "$command" in
        doctor) cmd_doctor "$@" ;;
        ssh) cmd_ssh "$@" ;;
        remote-check) cmd_remote_check "$@" ;;
        runai-list) cmd_runai_list "$@" ;;
        sync-code) cmd_sync_code "$@" ;;
        pull-results) cmd_pull_results "$@" ;;
        pull-artifacts) cmd_pull_artifacts "$@" ;;
        pull-checkpoints) cmd_pull_checkpoints "$@" ;;
        build-image) cmd_build_image "$@" ;;
        push-image) cmd_push_image "$@" ;;
        submit-interactive) cmd_submit_interactive "$@" ;;
        submit-smoke) cmd_submit_smoke "$@" ;;
        submit-train) cmd_submit_train "$@" ;;
        submit-cmd) cmd_submit_cmd "$@" ;;
        run-train) cmd_run_train "$@" ;;
        wait-job) cmd_wait_job "$@" ;;
        job-status) cmd_job_status "$@" ;;
        job-logs) cmd_job_logs "$@" ;;
        job-delete) cmd_job_delete "$@" ;;
        summarize-results) cmd_summarize_results "$@" ;;
        interactive-bash) cmd_interactive_bash "$@" ;;
        -h|--help|help) usage ;;
        *) usage; die "Unknown command: $command" ;;
    esac
}

main "$@"
